#
# Add comment.
#

bool ARMED=True			# vehicle armed
bool DISARMED=False		# vehicle disarmed
bool ON=True			# controller on
bool OFF=False			# controller off

bool armed				# values ARMED or DISARMED

bool x_ctrl				# values ON or OFF
bool y_ctrl				# values ON or OFF
bool z_ctrl				# values ON or OFF

bool vx_ctrl			# values ON or OFF 
bool vy_ctrl			# values ON or OFF
bool vz_ctrl			# values ON or OFF

bool yaw_ctrl			# values ON or OFF
bool vyaw_ctrl			# values ON or OFF

# TOPICS controllers_switch mcu_controllers_switch ctrl_sm_controllers_switch